before_install:
- sudo rm -f /etc/mavenrc
- export M2_HOME=/usr/local/maven
- export MAVEN_OPTS="-Dmaven.repo.local=$HOME/.m2/repository -Xms1024m -Xmx3072m"

install: true
jdk:
- oraclejdk8
language: java
sudo: false

addons:
  sonarcloud:
    organization: "hashmapinc-github"
    token:
        secure: "fcoReZvq0MHb2zLRkvWIZyvdApJRUcoalErrylo5B2SZ/Vg7Bbc1seCo5sbb/K02f+CdpompnRKtSDP0ULadxSIHZZMZZwV9Gm2xMiwNdlJ63xqE40SF8w24gL3s2RSL/udmc+lPHBMtmWt9nVfXfyUWt429jnNRJB+e8zYqEgSip9iKVjiaDM8ZfJ8RqR0Fz0ZTvhlPa33NDCszhIDsactxAW8yTkXxZ0IQ1MDyAdQ7AiGc+y7w0Iq+XFH9BKwBCXY7KbEwaESz9Hc4UtJcobS960d1fWklJNAUQplZQ3sS3Ga68Nvnwm5MmYUP1PWL7wDURTewf54xgWuRJ5hYRXUzHAMKDQyMxcYCYqg50Q40w5hJHKet1wctX5gr9CXvOH6JR9SlZGsqjVH/tVxZdDvcFm10MlNLHntREiTybdc7kNnRBCDdNTlUs2A68/fXQtl0agl82Y5hxf+qbczTFqnUE2lW2LbLgDL2whmhrwnMvoiy6Bt8srWaHGsQ9U5O5AhpPOW0eIoloHWpj/ZilDdpkNznkpG80BeByhIt2fMoGP2tFRtyElnscio+LXJialov7XJLr2WjM9J1Hz2irYoLACg6z3cojtkLKrWYJIKTAtqgmePp/pWkEkCPR+mzLVz8dsK5EO0z41YD8HM1n9CQ0UqqLXhtpYBvWH9O4Ww="
script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
  
before_deploy:
  - git tag -f "1.4.0-SNAPSHOT"

deploy:
  provider: releases
  api_key:
    secure: "KXCAuF5zg7je0OSJOyCcT6V6vv11FCb/VGVJkAnVYCYXvofx4a4Uxm4m6xqRCXp8WWJGzYKG0ivVuCdSDVk2+VvMzB6WGLISK3vyqUluHHx1JwMW/5GlO2DhbHuUjrMMlwZ9eWsJDAo4ANfckBrDdkUBc8glKw2kvq4XG6dyOuZe02zSCudcfxFahmsSWV8a1vannZyLfpHLvmcwqQQAZP2k1lSs0vHpjDyrXB31871Ff4J/LASj6QeZXHYuJXBHARrm8XFbUA1vnbdVY15QC5SLAAcr4BmJDIGup7vWicRohOMO0oSHA9Heewn+VNaemceGESVsxmgdJ+r4EAG8Qo++JC9m5Gk2yEBf8ZtlXEMvMwuZKJLPfcwcBXGcuplwyEwxgsj+Eyw9RUgLl2M8Tn4PtoOzNQjk6SC8U2wCxcD56h4b/jm/sUvGQWVkHJBuwmih9kOZlk5kE22R0rQL0GovbnHwi7u6bvTNER5YUEg+K1sWUWu7AjSjtTgf7pKVcvKuBT4a24nSpABINaD3gQIMpDGLvY3Lmn1tkS+Jr8LI8rAXZHZXBR0jkA/9YgLD7/Iz+iWFBv7FW2mvaWCNf2snxAb32iG2lKlpH298QlM/KK7bpaRbqjF+e26nXOHABPYW7xGpXotxTHBT/fhpWvZY781W2rYnRIz7ER0KvEw="
  file:
    - '$TRAVIS_BUILD_DIR/application/target/tempus.deb'
    - '$TRAVIS_BUILD_DIR/application/target/tempus.rpm'
    - '$TRAVIS_BUILD_DIR/application/target/tempus-windows.zip'
  skip_cleanup: true
  overwrite: true
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^master|dev$
